### ISSUE TITLE
[Chapter - 06] 왜 인터페이스 분리 원칙을 위반하는 것일까?

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#1]
#### 질문 내용을 적어주세요 📝

> 47p 하단이렇게 구현해 버리면 인터페이스 분리 원칙을 위반하게 됩니다

왜 인터페이스 분리 원칙을 위반하게 되는걸까요 ..?
예시까지 같이 작성해주시면 감사하겠습니당

**Comment by STACY-KH** [comment]
먼저 인터페이스 분리 원칙은, 객체가 자기 자신에게 필요한 기능(즉, 메소드)만 가지도록 해서, 사용할 수 없는(무의미한) 것을 불필요하게 상속, 구현하는 것을 최대한 막도록 하는 원칙인데요
책에서는 '사용할 수 없는' 이라고 되어 있는데,
제가 이해한 바로는 사용하면 문제가 생기는 건 아니나, 결국 쓸모 없는 메소드 라고 이해를 했습니다.


자동차로 예를 들어보겠습니다.
자동차 라는 객체는 보통 움직이는 `주행`의 기능, `에어컨`, `라디오`, `DMB`, `음악재생`, `자율주행` 등의 기능을 가지고 있습니다.
최근 10년 내 출시된 자동차를 생각했을 땐, 위의 기능이 모두 포함되어 있을 가능성이 높아 이 경우에는 문제가 되지 않을 수 있습니다.
그러나 위의 자동차 객체를 상속받아 만약 약 30년 전(?) 티코 같은 자동차를 구현해야 한다면, DMB, 음악재생, 자율주행 기능은 없고,
더 옛날 자동차에는 에어컨도 없겠죠?
그런데도 자동차 객체가 가지고 있는 모든 기능을 구현은 해야 하고, 그렇지만 `쓸모가 없는 == 책에서 말한 사용할 수 없는` 기능이 티코나 더 옛날 자동차에 포함되기 때문에, 이는 인터페이스 분리 원칙을 위반하게 되는 것입니다.

아래는 예시 코드 입니다.

```kotlin
interface Car {
    // 주행
    fun drive() {
        println("부릉부릉")
    }
    // 에어컨
    fun airConditioning(power: Int) {
        println("$power 세기로 에어컨 동작")
    }
    // 라디오
    fun radio(frequency: Double) {
        println("$frequency 라디오 재생")
    }
    // DMB
    fun dmb(channel: Int) {
        println("$channel 번 채널 시청 시작")
    }
    // MP3
    fun mp3() {
        println("노래 흥얼흥얼~~")
    }
    // 자율주행
    fun autoDrive() {
        println("자율주행 시작")
    }
}
```
```kotlin
class BenzS500 : Car {

    override fun drive() {
        // blabla..
    }

    override fun airConditioning(power: Int) {
        // blabla..
    }

    override fun radio(frequency: Double) {
        // blabla..
    }

    override fun dmb(channel: Int) {
        // blabla..
    }

    override fun mp3() {
        // blabla..
    }

    override fun autoDrive() {
        println("Benz Auto Driving...")
    }
}
```
```kotlin
class Tico : Car {

    override fun drive() {
        // blabla..
    }

    override fun airConditioning(power: Int) {
        // blabla..
    }

    override fun radio(frequency: Double) {
        // blabla..
    }

    override fun dmb(channel: Int) {
        println("Tico cannot do it")
    }

    override fun mp3() {
        println("Tico cannot do it")
    }

    override fun autoDrive() {
        println("Tico cannot do it")
    }
}
```

BenzS500 자동차는 모든 기능을 포함해서 만들어질 수  있어서 Car의 모든 기능이 구현되지만,
Tico의 경우 너무 옛날 모델이라 사용할 수 없는(쓸모 없는) 기능이 세 개나 있기 때문에
위와 같이 코드를 짜면 인터페이스 분리 원칙에 어긋난다고 볼 수 있습니다.
