### ISSUE TITLE
[Chapter - 06] IllegalArgumentExcpetion 은 왜 500 에러인가?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#10]
#### 질문 내용을 적어주세요 📝

IllegalArgumentException은 클라이언트가 호출한 Argument가 잘못되었다는 것인데,
왜 클라이언트에러 400이 아닌 서버 에러 500으로 내려주고 있는지 궁금합니다!

**Comment by STACY-KH** [comment]
먼저 어플리케이션에서 IllegalArgumentException 등과 같은 예외가 발생했을 때, 이 예외는 아래와 같은 흐름으로 퍼져 나갑니다.
`controller(예외발생) -> interceptor -> servlet -> filter -> WAS`
이 흐름 내에서 예외를 잡아서 별도로 처리하지 않으면 마지막 WAS까지 예외가 전달되고,
WAS는 Exception 을 서버가 처리하지 못한 에러라고 받아들여 status code 를 500으로 내려주게 됩니다.

그래서 IllegalArgumentException 과 같은 경우에 500 이 아닌 다른 status code로 에러를 내려주도록 하고 싶다면
exceptionhandler 와 같은 별도 처리를 통해 처리할 수 있습니다.
