### ISSUE TITLE
[Chpater - 12] 왜 DSL 코드는 연산자 오버로딩 규칙을 무시해도 될까?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#11]
#### 질문 내용을 적어주세요 📝

p.80~p.81부터 DSL을 설계할 때는 연산자 오버로딩 규칙을 무시할 수 있다고 하는데, 그 이유가 명확하게 나온 것 같지 않습니다.
왜 DSL을 설계할 때는 이렇게 규칙 파괴(?)가 가능한지 궁금합니다.

**Comment by seohw54** [comment]
DSL은 독립적인 문법과 의미를 가진 언어이기 때문에 연산자의 범용적인 의미에 맞지 않더라도 오버로딩을 허용할 수 있습니다.
말그대로 새로 규약을 정의하고 창조해낸 언어이기 때문에 오버로딩 규약에서 벗어날 수 있다는 의미인듯한데요~

근데 제가 받아들이기로는 아무리 DSL이라도 사용자에게 혼돈을 줄 정도로 규칙을 파괴해도 된다 라는 것이 아니라, 
맥락상 연산자를 잘못 이해할 일이 없을 정도내에서 관례에서 벗어날 수 있다 라고 이해했습니다.

예를들어, +연산자 (unaryPlus)가 범용적으로는 피연산자가 아직 숫자가 아닌 경우 숫자로 변환하려고 시도하는 연산자입니다.
```c
+true  // 1
+false // 0
+null  // 0
+function (val) { return val; } // NaN
+1n    //TypeError 발생:BigInt 값을 숫자로 변환할 수 없음
``` 

p.80 예제 코드로 나온 부분에서 고전적인 HTML DSL이 정확히 어떤것인지는 모르겠지만, 
맥락상 +"Some text" 앞의 +연산자가 Some test를 숫자로 변환하려는 unary plus 연산이 아닌 
div 의 속성값으로 Some text 문자열을 표기하기 위한 구분자나 다른의미로 받아들일 확률이 더 클것 같습니다.

```html
body {
div{
+"Some text"
}
}
```
