### ISSUE TITLE
[Chapter - 11] 회사 코드 내에서 가독성을 개선시킬 수 있는 포인트

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#12]
#### 질문 내용을 적어주세요 📝

읽다보니 회사 코드 중에서 공통적으로 개선시킬 수 있는 부분이 있을 것 같아서 이에 대해 같이 나눠보고 더 나은 개선점을 공유하면 좋을 것 같습니다. 코드를 여기에 올리기는 어려우므로 간단하게 예제코드를 넣거나, 설명만 댓글로 달고 코드는 스터디 시간에 봐도 될 것 같아요 ㅎㅎ

**Comment by sawooook** [comment]
음... 저는 pair 나 요런게 쓰는게 가독성이 안좋은것 같더라구요..! 
물론 DTO 파일이나 이런거 안만들어서 귀찮지 않고 좋기는 한데..

pair로 묶은 메서드를 다른 메서드로 넘기거나 하면... 오우 ..ㅠ 특히 Pair 로 묶은 애들이 String, Int 같은 타입일시...
뭐가 뭔지 몰라서 위에서 다찾아봤떤 기억이 있습니다

**Comment by eunq93** [comment]
저는 /** */을 사용해서 함수의 윗부분에 설명이 있었으면 좋겠네요.

또 하나는 메인 로직을 수행하는 함수는 좀 길어질 순 있어도  
그 외 단순한 기능을 수행하는 함수는 3~5줄 이내로 하는 방법도 있고요.

**Comment by sawooook** [comment]
아 하나더 생각났는데

객체지향 체조원칙 9가지 에서 저는 요거 두가지가 가독성을 조금더 높힌다고 생각합니당
1. 한 메서드에는 오직 한단계의 들여쓰기만 한다
```java
if (user.isBirth()) {
     if (user.orders.length()) { 
             .....
     }
}
```

2. else 키워드는 최대한 쓰지 않는다
#### before
```java
return if (user.isBoy()) {
     true
} else {
    false
}
```

#### after
```java
if (user.isBoy()) {
    return true
} 

return false
```

참고할자료 : 객체지향 체조 9가지 원칙
https://jamie95.tistory.com/99

**Comment by JungTag** [comment]
> 음... 저는 pair 나 요런게 쓰는게 가독성이 안좋은것 같더라구요..! 물론 DTO 파일이나 이런거 안만들어서 귀찮지 않고 좋기는 한데..
> 
> pair로 묶은 메서드를 다른 메서드로 넘기거나 하면... 오우 ..ㅠ 특히 Pair 로 묶은 애들이 String, Int 같은 타입일시... 뭐가 뭔지 몰라서 위에서 다찾아봤떤 기억이 있습니다

저도 요거 고민인데, Pair가 싫긴 한데 (특히 같은 타입끼리 묶을 때가 최악...) DTO를 매번 만들어야 하나? 그것도 좀 고민이더라구요
혹시 @sawooook 님만의 노하우가 있을까요??

**Comment by JungTag** [comment]
> 저는 /** */을 사용해서 함수의 윗부분에 설명이 있었으면 좋겠네요.
> 
> 또 하나는 메인 로직을 수행하는 함수는 좀 길어질 순 있어도 그 외 단순한 기능을 수행하는 함수는 3~5줄 이내로 하는 방법도 있고요.

@eunq93 
주석다는 게 지저분하다고 생각했었는데, 있는 게 확실히 코드 읽을 때 편리하더라구요. 저도 완전 공감하는 바입니다.
개인적으로 주석 같은 거는 룰로 정해서 같이 해보는 것도 좋을 것 같아요 ㅋㅋ

**Comment by STACY-KH** [comment]
저도 @eunq93 은규님 말씀처럼 주석 다는 것에 매우 동의합니다!
특히 저희 dcapi 만 봐도 하나의 함수가 코드가 단순하지 않으면 코드를 볼 때마다 코드 파악에 적지 않은 시간이 드는 것 같아요
그리고 또 함수가 redis를 조회한 데이터를 주는지, db인지, 아님 둘다 왔다갔다 해서 가져오는 데이터인지...헷갈리더라구요
(물론 제 머리가 나빠서 그럴수도 있습니다ㅋㅋ)

**Comment by sawooook** [comment]
> > 음... 저는 pair 나 요런게 쓰는게 가독성이 안좋은것 같더라구요..! 물론 DTO 파일이나 이런거 안만들어서 귀찮지 않고 좋기는 한데..
> > pair로 묶은 메서드를 다른 메서드로 넘기거나 하면... 오우 ..ㅠ 특히 Pair 로 묶은 애들이 String, Int 같은 타입일시... 뭐가 뭔지 몰라서 위에서 다찾아봤떤 기억이 있습니다
> 
> 저도 요거 고민인데, Pair가 싫긴 한데 (특히 같은 타입끼리 묶을 때가 최악...) DTO를 매번 만들어야 하나? 그것도 좀 고민이더라구요 혹시 @sawooook 님만의 노하우가 있을까요??

@JungTag 
엇 딱히 노하우는 없고 그냥 들었던 생각은,,, 넘기는 값이면 DTO를 만들고, 한 메소드내에서만 사용할때는 Pair 를 사용해야겠다 ..? 라고만 생각하고 있숩니다..!

**Comment by JungTag** [comment]
제가 생각했던 개선 포인트는 다음과 같습니다.

1) 무조건적으로 scope function을 사용하는 것을 지양하자. 과도한 scope function은 가독성을 심하게 떨어뜨릴 수 있기에, 적절한 선에서 분리하는 게 좋을 것 같습니다. 그리고 람다 함수를 중첩으로 사용할 때는 수신객체명으로 it을 사용하기 보다는 변수명을 직접 지정해주는 게 좋을 것 같습니다~~
```kotlin
// Bad
foo?.let {
...
}.also {
...
}.run {
...
}

// Bad (억지 예제라서 위 아래 둘 다 이상하긴 합니다. 명시적인 변수명을 사용한다는 것만 봐주세요)
fun processUser(user: User?) {
    it?.let {
        // user를 사용하여 작업 수행
        println("User name: ${it.name}")
        
        it.orders?.let {
            // orders를 사용하여 작업 수행
            it.forEach {
                // order를 사용하여 작업 수행
                println("Order id: ${it.id}")
            }
        }
    }
}

fun processUser(user: User?) {
    user?.let { user ->
        // user를 사용하여 작업 수행
        println("User name: ${user.name}")
        
        user.orders?.let { orders ->
            // orders를 사용하여 작업 수행
            orders.forEach { order ->
                // order를 사용하여 작업 수행
                println("Order id: ${order.id}")
            }
        }
    }
}
```
2) 객체 변환 시에 apply 함수를 사용하기 보다는 의미있는 정적 팩터리 함수를 사용하자
```kotlin
// Bad
fun After.apply(before: Before): After {
    return this.apply {
        a = before.a
        b = before.b
        ...
    }
}
After.apply(before) // use

// Better
companion object {
    fun ofBefore(before: Before): After {
        return After(
            a = before.a
            b = before.b
            ...
        )
}
After.ofBefore(before) // use
```
3) 최대한 로직을 도메인에 밀어넣자 + 모든 로직을 서비스에 넣기 보다는 추상화 과정을 거쳐서 적절한 객체에 책임을 부여하기
4) 객체 생성을 먼저하고 setter를 호출하는 방식

**Comment by ozzing** [comment]
> 1. 한 메서드에는 오직 한단계의 들여쓰기만 한다
> 2. else 키워드는 최대한 쓰지 않는다

저도 if문 안 내용이 길어지거나 if문의 depth가 깊을 수록 코드를 읽고 파악하는데 시간이 너무 오래걸려 힘들었던 기억이 있습니다...!
타입과 같이 조건이 명시적이어서 else의 사용이 필요한 경우가 아니라면, 아래처럼 완전히 early return 구조를 사용하는 것도 개인적으로 보기 편하다고 생각합니당

**BEFORE**
```kotlin
return if (user.isMan()) {
     false
} else if (user.isWoman()) {
     false
} else {
     true
}
```

**AFTER**
```kotlin
if (user.isMan()) {
     return false
}
if (user.isWoman()) {
     return false
}
if (user.isChild()) {
     return true
}
```
