### ISSUE TITLE
[Chapter - 10] private 메소드도 테스트를 해야할까?

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#14]
#### 질문 내용을 적어주세요 📝

private 메소드도 테스트를 해야할까요?! 

private 내부 로직이 복잡하면 미친듯이 하고싶을때가 있지 않나여 ..?

저희팀은 심지어 코틀린을 쓰니... mockk를 쓸테고 private method 테스트가 쉽던데 ... 

이런상황에서는 어떻게 하는지 이야기 해보면 좋을 것 같습니다 !

https://www.facebook.com/groups/javawocky/posts/930613100327033/

**Comment by sawooook** [comment]
옛날에 영일님이랑 요거에 대해서 이야기 나눴었는데요...! 

결론은 하지 말자 였습니다.

1.  private 는 캡슐화하려고 감춘 것 인데 이걸 강제로 리플랙션이나 이런걸 이용해서 테스트한다..? 
2. 대부분 그런상황에서는 클래스가 비대해진 것 이기에 분리해서 테스트하는것이 좋다
3. `private -> public` 으로 바꿔서 한다 ? 흠 ... 이건 진짜 아니다

저번에 플젝하면서 로직작성하다가 private 메소드가 여러개 생기고 내부가 엄청 복잡해서 public으로 모든 테스트를 다 작성하기 버겁더라구요...! ㅜ
저는 그래서 요런상황에서 클래스를 분리하여 로직을 작성해서 테스트 했었었습니당..!


근데 굳이 클래스가 비대하지도 않아 분리하기 쫌 그러면 mockk 이용해서 해봐도 좋을것 같긴 하네용..!

1. mockk private method 
+ https://velog.io/@miot2j/Kotlin-mockk%EC%9C%BC%EB%A1%9C-private-%EB%A9%94%EC%86%8C%EB%93%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%95%98%EA%B8%B0-Slot-%EC%82%AC%EC%9A%A9%EB%B2%95

2. private 메서드 테스트하지마세요!
+ https://fishbowl.pastiche.org/2003/03/28/testing_private_methods_dont_do_it

**Comment by JungTag** [comment]
저 또한 @sawooook 님께서 말씀하신 내용에 깊이 공감합니다.

[단위 테스트](https://www.yes24.com/Product/Goods/104084175)라는 책에서 관련한 내용이 나오네요. (p.372~) 
짧게 정리하자면 다음과 같습니다. (사욱님께서 너무 잘 적어주셔서 책 내용만 덧붙였습니다)

- **비공개 메서드 테스트는 절대 하지 말아야 한다**
  - 기본적으로 공개 메서드만이 (외부에서) 식별할 수 있는 동작이다
  - 결국 비공개 메서드를 테스트하는 것은 단위 테스트의 기본 원칙 중 하나인 식별할 수 있는 동작만 테스트하는 것을 위반한다
- **예외적으로 비공개 메서드의 테스트가 타당한 경우가 있다. (ex) 생성자에서 validation)**
  - 근데 책에서 결국 제대로 설명은 안 해주고 공개 메서드로 바꾸거나, 공개로 바꾸기 싫으면 테스트할 때 리플렉션 사용하는 걸 고려하라고 한다
- **비공개 메서드 테스트가 필요한 경우는 추상화가 누락됐기 때문이다**
  - 별도의 클래스로 분리하자

저는 비공개 메서드를 테스트하지는 않았는데, 모킹처리가 필요하다고 느껴지는 경우가 종종 있는 것 같습니다. 그럴 때마다 이 내용을 기억하고 적용해봐야겠네요 👍
