### ISSUE TITLE
[Chapter - 12] DSL 은 무엇일까요?!

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#15]
#### 질문 내용을 적어주세요 📝

12장 책을 보게 되면 DSL 에 대한 설명이 여기저기에 나오더라구요..!

DSL이 무엇이고,  어떤상황에서 사용하면 좋고, 사용하게 되면 장점과 단점, 사용해보셨으면 그 때 그 느낌...(?)

요렇게 궁금합니다 ~~!

**Comment by seohw54** [comment]
도메인 특화 언어(Domain Specific Language)는 일반적인 범용 언어 (자바, 코틀린, C++ 등) 에 반대되는 개념으로, 
특정 도메인의 목적을 위해 고안된 언어입니다. 

DSL은 비즈니스 로직을 간결하게 작성할 수 있고, 여러 개발자들이 같은 코드를 작성하는 반복을 피할 수 있는 장점이 있습니다.
하지만 DSL을 설계하는것이 까다롭고 새로운 언어이기 때문에 매번 습득해야된다는 단점이 있습니다.

흔히 볼 수 있는 예시로, queryDSL 은 쿼리문 작성이라는 비즈니스 로직에 특화된 언어입니다.
다들 잘 아시겠지만 queryDSL은 JPA만으로 해결하지 못하는 복잡한 쿼리를 sql문법에 해당되는 메소드들을 제공해줘서
동적으로 SQL 쿼리를 작성할 수 있고 type-safe가 보장될 수 있습니다.

쿼리문이라는 비즈니스에 특화된 언어이기 때문에, 자바(또는 코틀린) 코드의 쿼리메소드(where, eq, inner join 등)가 SQL 문법과 비슷하여 코드 이해가 잘된다는 점에서 만족스럽긴 했으나, 
추가 우회 계층으로 도메인 모델을 감싸서 만든 언어이기 때문에, 내부적으로 실제 쿼리문이 어떻게 작성되는지는 파악하기가 어려운 점이 있었습니다.

DSL에 대한 예시가 잘 설명된 블로그가 있어 공유드립니다!
https://worker-investor.tistory.com/64
