### ISSUE TITLE
[Chapter - 10] TDD에 대해서

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#16]
#### 질문 내용을 적어주세요 📝

p.66에서 테스트 기반 개발 방식이 언급되었는데요~!

다들 TDD에 대해서 어떻게 생각하시는지..
혹시 업무 코드에서 실제로 적용해본 사례 공유해주실 분 계실까요?!

**Comment by sawooook** [comment]
저번에 결수즉 프로젝트할때 TDD 해볼려고 초기에 해봤었는데, 하다가 접었었습니다..
익숙하지 않아서 그런지 계속 로직부터 작성하려고하고, 그담 뭘 해야하지 이러면서 멍때리고 있더라구요 ...?
연습을 하면 괜찮을 것 같긴한데 ... 좀 저랑은 잘 안맞았던 것 같습니다..! ㅜ

음 TDD에 대해서는 하면 좋긴하지만,,, 필수는 아니라고 생각합니다

**Comment by JungTag** [comment]
Q) TDD에 대해 어떻게 생각하는지?
- 좋은 개발 법칙은 맞다고 생각하지만, 반드시 지켜야 하는 룰은 아니라고 생각합니다
- 개인적으로 TDD Cycle 중에 RED 까진 아니더라도 Green -> Refactor 정도까지는 지켜주는 게 좋은 것 같습니다
  - TDD cycle: Red(실패하는 테스트 작성) -> Green(최소한의 코드 작성을 통한 테스트 통과) -> Refactor(리팩토링)

개인적으로는 TDD 자체가 중요하다기 보다는 TDD의 목적이 중요하다고 생각합니다. 다양한 부가적인 가치가 있겠지만, 제일 중요한 건 코드의 내구성이 강해지게끔 만드는 것 같아요. 꼭 TDD로 개발을 하진 않더라도, 테스트 코드는 꼭 작성해서 유지보수성을 높였으면 하는 바람입니다!

+ 실무에서 간단한 로직 같은 경우엔 TDD를 적용해본 적은 있는데, 핵심적인 도메인들에 대해서 작성했던 건 아니라서 크게 의미있진 않았던 것 같습니다...!! 코드 작성 전에 설계 과정을 충분히 거쳐서 객체를 잘 설계할 때 TDD가 비로소 의미있는 것 같아요..ㅎㅎ

**Comment by ozzing** [comment]
저는 실무에서의 경험은 없고 프로젝트 하면서 TDD를 적용해 본 적이 있었는데요, 개인적으로는 영택님이 위에 자세히 적어주신 TDD Cycle 중 Red 단계가 굉장히 유용했던 것 같아요!
성공 케이스는 많이 테스트 해보는 반면, 반드시 실패해야 하는 케이스가 다른 코드의 변경으로 인해 성공 되었던 적이 있었습니다 🥲
저도 반드시 지켜야 하는 룰이라고 생각하지는 않지만, 놓칠 수 있는 부분들을 사전에 방지할 수 있다는 점이 좋았던 것 같아요..!

**Comment by STACY-KH** [comment]
저도 TDD에 대해서는 사욱님이나 영택님 말씀처럼 좋은 개발 법칙(또는 그냥 개발 법칙 중 하나..)이긴 한데 필수는 아니라고 생각합니다!
저는 TDD의 목적은 알겠으나, 어떤 개발 법칙을 적용해서 개발을 하더라도 
- 사용자의 요구사항 변화에 따른 설계나 개발 변경은 불가피하고
- 결국 사람이 하는 일이라 어쩔 수 없이 오류가 발생할 수 있다고 생각합니다

그런 의미에서 저는 개발 법칙과 무관하게 개발 전에 요구사항 분석과 설계를 `명확하고` / `변화에 유연하고` / `확장이 쉽도록` 해서
개발도 이처럼 진행될 수 있도록 하는 것을 선호합니다.
그리고 물론 테스트코드도 반드시 작성하는 게 좋다고 생각합니다.
TDD의 장점 중에 `개발이 완료되면 테스트코드를 작성하는게 귀찮기 때문` 이라는 내용이 있는데, 이건 그저 개발자의 문제일 뿐, 개발 법칙과는 무관한 것 같아요ㅋㅋ
