### ISSUE TITLE
[Chapter - 11] let을 사용한 비용 높은 예시 코드 개선하기

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#17]
#### 질문 내용을 적어주세요 📝

p.74에서 let을 사용하는 예시에서 디버그하기 어렵고 이해하기 어려운 예시 코드를 들었는데요~
그럼 해당 코드를 비용 낮은 (= 디버그하기도 쉽고 이해하기 쉬운) 코드로 어떻게 변환할 수 있을까요?

```kotlin
students.filter { it.result >= 50 }
    .joinToString { seperator = "\n" } {
        "${it.name} ${it.surname}, ${it.result}"
    }
    .let(::print)
``` 

```kotlin
var obj = FileInputStream("/file.gz")
  .let(::BufferedInputStream)
  .let(::ZipInputStream)
  .let(::ObjectInputStream)
  .readObject() as SomeObject
```

**Comment by ozzing** [comment]
일단 책에 나와있듯이 이 경우에는 let을 사용하는 비용을 지불할만한(복잡성이 어느정도 정당한) 코드라고 생각이 듭니다!

---

그 이유는 1번 예시의 경우, 마지막으로 실행되는 print 함수를 가장 오른쪽에 배치함으로써 코드의 순서 파악이 가능해 더 편리하기 때문입니다. 
예시의 print문은 익숙하지만, 그렇지 않은 경우에 안쪽 함수의 결과를 파악하고 이후 바깥 쪽 함수를 실행하는 아래 코드에 비해 훨씬 간결합니다. 
```kotlin
print(students.filter { it.result >= 50 }
    .joinToString { separator = "\n" } {
        "${it.name} ${it.surname}, ${it.result}"
    })
```
사실 엄청나게 개선할 수 있는 방법은 떠오르지 않는데요...ㅠ 
책의 아이템17을 참고하면 이름 있는 아규먼트를 아래와 같이 명시적으로 사용해 가독성을 더 높일 수 있을 것 같습니다!
또는 완전히 변수로 나누어주게되면 조금 더 가독성있지 않을까 생각이 됩니당
더 좋은 방법 있으신 분들 의견 주시면 감사하겠습니다~!

```kotlin
val separator = "\n"
val result = students.filter { it.result >= 50 }.joinToString(separator) {
        "${it.name} ${it.surname}, ${it.result}"
    }
print(result)
```

---

2번의 경우 저는 개인적으로 + 서치해본 결과 가독성이 아래와 같은 코드보다 좋다고 생각되는데, 좋은 개선 방안이 있으면 말씀주시면 감사하겠습니다!
```kotlin
var notification: NotificationComponent = BaseNotification()
notification = LargeIconDecorator(notification, image)
notification = BigPictureDecorator(notification, image)
notification.createNotificationBuilder(this, pendingIntent, title, body, CHANNEL_ID)
```
