### ISSUE TITLE
[Chapter - 05] contract란?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#2]
#### 질문 내용을 적어주세요 📝
```
public inline fun require(value: Boolean): Unit {
    contract {
        returns() implies value
    }
    require(value) { "Failed requiredment." }
}
```

p.42에 등장하는 contract 키워드의 기능과 그와 관련된 @OptIn 애너테이션란 어떤 것일까요?
ref) https://youtu.be/LFmF6kuYItc

**Comment by seohw54** [comment]
contract 키워드는 Kotlin 1.3 부터 도입되었고, 말그대로 컴파일러와 개발자간의 계약입니다.
계약의 내용은 아래와 같습니다.

```
contract 블록 안의 implies 조건을 만족하는 경우 returns() 괄호 안에 있는 값을 리턴하기로 한다.
``` 

따라서 적어주신 p.42 코드는 value 조건이 true일 경우 리턴을 하기로 계약한 것이고, 
require(value) {"Failed requiredment."} 코드에 의해 value가 false인 경우 해당 메세지로 IllegalArgumentException이 발생합니다.
(참고로, 리턴할 수 있는 값은 true,false,null 이며, 예제 코드처럼 void로 리턴할 수 있습니다.)

주의할 점은 contract문은 항상 첫번째 구문에 작성해야 밑의 코드에 계약 내용을 적용할 수 있습니다.

하지만 실제로 예제 코드를 실행해보려면 아래와 같이 컴파일 오류가 발생합니다.

This declaration is experimental and its usage must be marked with '@kotlin.contracts.ExperimentalContracts' or '@OptIn(kotlin.contracts.ExperimentalContracts::class)'

<img width="1163" alt="스크린샷 2023-07-06 오후 9 59 43" src="https://github.com/ko-auction/effective-kotlin/assets/138177814/69a558bb-bdaa-4506-8670-fa86b4e3102a">

이러한 이유는 contract 기능 자체가 아직은 실험적인 베타 기능이기 때문에 OptIn 어노테이션을 붙여 명시를 해줘야합니다.

<img width="411" alt="스크린샷 2023-07-06 오후 10 05 33" src="https://github.com/ko-auction/effective-kotlin/assets/138177814/bd69b87d-4cc3-4a1f-83cf-a2036c97c3b0">

OptIn 어노테이션은 특정 기능을 사용하기 위해 명시하는것으로 "안정되지 않은 버전의 기능을 사용하는데 동의한다" 라고 이해하면 될듯합니다.
