### ISSUE TITLE
[Chapter - 15] 코틀린 label

### ISSUE THREAD

**Issue by audgnssweet** [ko-auction/effective-kotlin#20]
코틀린 label 이란 무엇일까요?

**Comment by audgnssweet** [comment]
아래 출처를 번역한 내용입니다
https://kotlinlang.org/docs/returns.html#break-and-continue-labels

# Break and continue labels

코틀린의 모든 표현식은 label로 표시될 수 있습니다. 
label은 abc@ 또는 fooBar@와 같은 @ 기호 뒤에 식별자의 형태를 가집니다. 
표현식에 레이블을 지정하려면 표현식 앞에 label을 추가하세요.

```kotlin
loop@ for (i in 1..100) {
    // ...
}
```

break 와 continue 를 label 과 함께 사용할 수 있습니다.

```kotlin
loop@ for (i in 1..100) {
    for (j in 1..100) {
        if (j == 5) break@loop

        println("i = $i, j = $j")
    }
}

//실행결과
i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 1, j = 4

loop@ for (i in 1..5) {
    for (j in 1..100) {
        if (j == 2) continue@loop

        println("i = $i, j = $j")
    }
}

//실행결과
i = 1, j = 1
i = 2, j = 1
i = 3, j = 1
i = 4, j = 1
i = 5, j = 1
```

break 는 label 직후의 코드로 이동하고
continue 는 label 붙은 loop 를 반복합니다.

# Return to labels

Kotlin에서는 function literal, local function 및 object expression 등을 사용하여 함수를 중첩할 수 있습니다. 
람다 식에서 return 을 하게되면, 가장 가까운 함수를 빠져나가게 됩니다.
(참고로 이게 가능한건, inline function 때문입니다)
아래 코드를 봅시다.

```kotlin
listOf(1, 2, 3, 4, 5).forEach {
    if (it == 3) return // foo()에서 return
    print(it)
}
println("이 코드는 실행되지 않습니다.")

//실행결과
12
```

람다 함수에서만 빠져나오고 싶다면, label 을 사용해야 합니다.

```kotlin
listOf(1, 2, 3, 4, 5).forEach lit@{
    if (it == 3) return@lit // 람다식(forEach loop)에 대한 local return
    print(it)
}
print("명시적 label을 사용한 코드")

//실행결과
1245명시적 label을 사용한 코드
```

lambda 가 넘겨지는 함수의 이름을 그대로 label 로 사용하는
묵시적 label 도 있습니다.

```kotlin
listOf(1, 2, 3, 4, 5).forEach {
    if (it == 3) return@forEach // 람다식(forEach loop)에 대한 local return
    print(it)
}
print("명시적 label을 사용한 코드")
```

anonymous function 을 사용하면, 해당 익명함수를 종료하게 되어
label 을 붙인것과 같게 됩니다.

```kotlin
listOf(1, 2, 3, 4, 5).forEach(fun(value: Int) {
    if (value == 3) return  // local return to the caller of the anonymous function - the forEach loop
    print(value)
})
print(" done with anonymous function")

//실행결과
1245 done with anonymous function
```

위의 예제들은 람다의 해당 반복만 빠져나오므로 마치 일반 반복문의 continue 처럼 동작합니다.

일반 반복문의 break 처럼 동작하려면 다른 중첩 lambda 를 활용하면 됩니다.

```kotlin
run loop@{
    listOf(1, 2, 3, 4, 5).forEach {
        if (it == 3) return@loop // non-local return from the lambda passed to run
        print(it)
    }
}
print(" done with nested loop")

//실행결과
12 done with nested loop
```

마지막으로 label Return 시에 반환값을 지정할 수 있습니다.

```kotlin
val res = run loop@{
    listOf(1, 2, 3, 4, 5).forEach {
        if (it == 3) return@loop "hi" // non-local return from the lambda passed to run
        print(it)
    }
}
print(" done with nested loop. res = $res")

//실행결과
12 done with nested loop. res = hi
```

# label return decompile

case 1. normal return
```kotlin
listOf(1, 2, 3, 4, 5).forEach {
    if (it == 3) return
    print(it)
}
println("이 코드는 실행되지 않습니다.")
```

![image](https://github.com/ko-auction/effective-kotlin/assets/19279163/3c237685-938c-4b1d-8af0-b595e1f0bc01)

case 2. label return
```kotlin
listOf(1, 2, 3, 4, 5).forEach {
    if (it == 3) return@forEach
    print(it)
}
println("이 코드는 실행되지 않습니다.")
```
![image](https://github.com/ko-auction/effective-kotlin/assets/19279163/2ef1e23a-5996-4fd0-b808-fffe22526c9f)


# 참고자료
[kotlin label?](https://velog.io/@sangh00n/%EC%BD%94%ED%8B%80%EB%A6%B0-Label-%ED%91%9C%ED%98%84%EC%8B%9D)
[kotlin function literal?](https://medium.com/depayse/kotlin-%ED%95%A8%EC%88%98-%EB%A6%AC%ED%84%B0%EB%9F%B4-function-literal-1-%EC%9D%BC%EA%B8%89-%EA%B0%9D%EC%B2%B4-first-class-citizen-44cdd64b1abe)
[kotlin function literal - lambda](https://medium.com/depayse/kotlin-%ED%95%A8%EC%88%98-%EB%A6%AC%ED%84%B0%EB%9F%B4-function-literal-2-%EB%9E%8C%EB%8B%A4-lambda-d710f3f45250)
[kotlin function literal - anonymous function](https://medium.com/depayse/kotlin-%ED%95%A8%EC%88%98-%EB%A6%AC%ED%84%B0%EB%9F%B4-function-literal-3-%EC%9D%B5%EB%AA%85-%ED%95%A8%EC%88%98-anonymous-function-8741783376cc)
[kotlin object expression](https://rnathsus.tistory.com/335)
[kotlin inline function](https://codechacha.com/ko/kotlin-inline-functions/)

**Comment by sawooook** [comment]
오옹 멋져요
