### ISSUE TITLE
[Chapter - 16] 백킹필드란 무엇일까요?!

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#21]
#### 질문 내용을 적어주세요 📝

92p 에 `백킹필드` 라 고 나오는데  요게 어떤건가요?!? 
예제를 보니 field라고 나오던데 이녀석의 정체도 궁금합니다

```
    class User {
        val name: String? = null
            get() = field?.uppercase()
    }
```

**Comment by eunq93** [comment]
우선 Kotlin에서 어떻게 클래스 내 속성(Propoty)이 JVM으로 변환되는지 확인하고 추가적인 설명을 하겠습니다.

```
class SampleClass {
    private var test1 = 0;
    private val test2 = 0;
    var test3 = 0;
    val test4 = 0;
}
```

이런 클래스가 있다고 하면 JVM에선 다음과 같이 변환됩니다.

```
public final class SampleClass {
   private int test1;
   private final int test2;
   private int test3;
   private final int test4;

   public final int getTest3() {
      return this.test3;
   }

   public final void setTest3(int var1) {
      this.test3 = var1;
   }

   public final int getTest4() {
      return this.test4;
   }
}
```

자세히 보면 코틀린 private 접근제어자가 있으면 get,set을 자동으로 생성하지 못하고 있고.
private 접근제어자가 없으면  코틀린에선 기본적으로 get()을 만들어 주고, val로 정의된 속성은 set() 까지 만들어 주고 있습니다.

------------

그럼 여기서 코틀린에 val (수정을 못하게) 하는 프로퍼티에 set() 함수를 임의로 지정하면 어떻게 될까요?
```
class SampleClass_2 {
    val test = 0
        set(value) {
            field = value
        }
}
```
Intelij에서는 
**A 'val'-property cannot have a setter**
란 에러문구가 나오고 있습니다.
 
우선 여기까지 어떻게 코틀린 속성값이 JVM에서 변환되는지 알 수 있었습니다.

----------------

답변을 하기전 마지막으로 속성이라는게 객체지향 프로그래밍에서 필드 + 메소드의 집합이라고 생각을 하죠 
https://en.wikipedia.org/wiki/Property_(programming)

---------------

백킹 필드를 알아보도록 합시다.

공식 문서는 다음과 같이 나와 있습니다.
https://kotlinlang.org/docs/properties.html#backing-fields
```
In Kotlin, a field is only used as a part of a property to hold its value in memory. Fields cannot be declared directly. However, when a property needs a backing field, Kotlin provides it automatically. This backing field can be referenced in the accessors using the field identifier:
```
우선 필드값은 직접 선언할 수 없고, 코틀린에서 필요하다면 자동으로 생성해주는 필드를 백킹필드라고 합니다.
이 필드값으로 접을 수 할 수 있게 해주는게 바로 **fields** 라는 식별자이고요.

```
var counter = 0 // the initializer assigns the backing field directly
    set(value) {
        if (value >= 0)
            field = value
            // counter = value // ERROR StackOverflow: Using actual name 'counter' would make setter recursive
    }
```

위 코드에서 filed를 통해서 Int counter로 직접 접근할 수 있습니다.
