### ISSUE TITLE
[Chapter - 15]  @DslMarker 메타 어노테이션의 다른 예시?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#22]
#### 질문 내용을 적어주세요 📝
p.90에서 코틀린 DSL에서 외부 리시버를 사용하는 것을 막기 위한 예시로 HtmlDsl을 들었는데요~
HtmlDsl 이 생소하다보니, 혹시 저희가 흔히 사용하는 DSL 중에서 볼 수 있는 DslMarker 예시가 있을지 궁금합니다!

**Comment by audgnssweet** [comment]
DslMarker 어노테이션
=> 중첩된 람다에서 외부 람다의 수신 객체를 접근하지 못하게 제한
