### ISSUE TITLE
[Chapter - 14] 변수 타입이 동적으로 변할 수 있는 경우?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#23]
#### 질문 내용을 적어주세요 📝
변수 타입이 명확하지 않을 경우 타입을 지정하라고 나와있는데용!

아래와 같이 변수 타입이 동적으로 변할 수 있는 상황에서는 명시하기가 어려울것 같은데, 타입을 지정하지 않아도 괜찮을까요?

그리고 코틀린의 타입 추론은 컴파일시점에 되는것으로 알고있는데, 
아래 상황과 같은 경우에는 어떤 타입으로 추론되고 컴파일이 되는것일지 궁금합니다!

```kotlin
val result = if (myCheck()) {
        42
    } else {
        "Error"
    }
```

**Comment by JungTag** [comment]
일단 기본적으로 Any로 추론되긴 하는데, 디컴파일 해보니 되게 재밌게 동작하네요 ㅋㅋㅋ

1) 컴파일 시점에 조건식의 결과를 판별할 수 있는 경우 -> 결과를 바로 대입, but 타입은 Object
```kotlin
val result = if (1 > 2) {
    42
} else {
    "Error"
}
```
![image](https://github.com/ko-auction/effective-kotlin/assets/29058347/b986f296-da1e-4303-a77b-f00748e22068)

2) 컴파일 시점에 조건식의 결과를 판별할 수 없는 경우 -> 삼항 연산자 사용, 타입은 Object
```kotlin
val result = if (getRandomNum() > 5) {
    42
} else {
    "Error"
}

fun getRandomNum(): Int {
    return (1..10).random()
}
```
![image](https://github.com/ko-auction/effective-kotlin/assets/29058347/d9a9d80e-9ee4-4457-83f3-035e9db2384e)

**Comment by sawooook** [comment]
A1. 예시로 적어주신 상황은 `Any` 를 적어주는것이 좋을 것 같습니다..! 

요런 상황은 자주 사용되지 않으니 다른사람들이 이거 뭐지 ..? 라고 생각할 수 있다 생각합니다

그래서 `Any`를 의도적으로 명시해 "나 일부러 이렇게 한거야" 라고 느낌을 내면 좋을것 같다는 개인적인 생각입니다 ...ㅋㅋㅋㅋ


A2. 영택님이 말씀주신것처럼 Any로 추론됩니다..!

무조건 Any로 추론되는 건가 싶어서 찾아보니 Double이랑 Int는 Number가 상위 클래스더라구용 혹시 몰라 해보니 ...


<img width="641" alt="image" src="https://github.com/ko-auction/effective-kotlin/assets/43979984/26b42d93-f07c-4399-b2a8-4fdf912ce2bb">


### 코드
```
    val result = if (getRandomNum() > 5) {
        42
    } else {
        10.0
    }

    fun getRandomNum(): Int {
        return (1..10).random()
    }
```

### decompile
```
   @NotNull
   private final Object result = this.getRandomNum() > 5 ? 42 : 10.0;

   @NotNull
   public final Object getResult() {
      return this.result;
   }

   public final int getRandomNum() {
      byte var1 = 1;
      IntRange var2 = new IntRange(var1, 10);
      return RangesKt.random(var2, (Random)Random.Default);
   }
```

무조건  `Object` 더라구여..!

추가로 `Double`과 `Int`가 공존하는 동적타입일때는 `Number`로 명시해줘서 
좀더 범위가 작은 타입을 쓰는게 좋을 것 같습니다..!

```
    val result : Number = if (getRandomNum() > 5) {
        42
    } else {
        10.0
    }

    fun getRandomNum(): Int {
        return (1..10).random()
    }
```
