### ISSUE TITLE
[Chapter - 16] 코틀린에서는 interface에도 프로퍼티를 정의할 수 있는 이유?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#24]
#### 질문 내용을 적어주세요 📝
p.93의 내용중에 코틀린에서 인터페이스의 프로퍼티를 정의하게된 이유에 대해 아래와 같이 간략하게 나와있는데요!

"프로퍼티는 필드가 필요 없습니다. 오히여 프로퍼티는 개념적으로 접근자를 나타냅니다. 
따라서 코틀린은 인터페이스에도 프로퍼티를 정의할 수 있습니다"

이 내용만으로 정확히 이해가 되지 않아서, 좀더 상세한 이유가 궁금합니다. 
그리고 자바와 달리 인터페이스에서 프로퍼티 정의를 허용함으로써 얻을 수 있는 이점이 궁금합니다!

```kotlin
interface Person {
 val name: String
}
```

**Comment by eunq93** [comment]
OOP에서 프로퍼티는 필드 + 메소드라고 생각하시면 됩니다.
실제로 인터페이스에서 위 코드와 같이 선언하면 JVM에서 다음과 같이 변환됩니다.
```
public interface Person {
   int getName();
}
```

속성을 초기화한다면 에러가 나옵니다.
그 이유는 interface내 속성을 정의하면 filed값이 없기 때문이죠.

저 Person interface를 사용할려면 하위 클래스는 val name : String 을 초기화 해야 됩니다.
```
class TestClass : Person{
    override val name: Int = 0
}
// 위 아래 둘 중 하나로.
class TestClass(override val name: Int) : Person{

}
```

우선 제 생각에는
해당 프로퍼티가 interface를 상속받는 곳에 반드시 있어야 한다면 
위와 같이 interface에 프로퍼티를 정의 하는 것 같습니다.

예)
Person에 있는 name이란 프로퍼티가 Student, Teacher등 하위 클래스에 name 프로퍼티가 정의해야 하는 경우.
