### ISSUE TITLE
[Chatper - 15] 왜 nullable 값을 처리할 땐 also나 let을 사용하는 게 좋은가?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#25]
#### 질문 내용을 적어주세요 📝

also나 let은 그 동작이 각각 apply, run과 동일합니다. 그런데 왜 nullable 값을 처리할 땐 also나 let을 사용하는 게 훨씬 좋은 선택지인지 궁금하네용

**Comment by audgnssweet** [comment]
저의 개인적인 의견이니, 참고만 해주시면 될 것 같습니다

아시겠지만
also, let 과 apply, run 의 차이점은
수신객체가 this 로 고정되어있는지 아닌지의 차이입니다.

이 책에서
안정성의 null 처리 파트에서가 아니라
굳이 이 파트에서 말씀하신 내용을 언급한 이유는

문맥상 **가독성** 때문이라고 생각합니다.

---

특히 이 책에서는 "한 스코프에 같은 이름의 수신객체 여러개" 가 나오는 상황을 조심해야 한다고 말하고 있습니다.

그런 관점에서 apply, run 은 this 라는 이름의 수신객체로 고정되기 때문에,
스코프가 중첩되는 상황, 특히나 언급된 **nullable 값을 처리할 때** 
무엇이 진짜 수신객체인지 코드를 자세히 들여다보는 경우가 생길 수 있습니다.
=> 가독성이 떨어짐
(nullable 뿐 아니라 스코프 중첩시에 내부 this, 외부 this 를 구분하게 되는 순간 가독성은 떨어진다고 생각합니다)

책에서 소개된 예제는, 이에 대한 가장 적절한 예시라고 생각합니다.

---

사실 스코프가 중첩되지 않은 단순한 상황에서 null 관련 처리를 할 때는
무엇을 사용하든 가독성 측면에서 별 차이가 없을것이라 생각합니다.

추가로 저는 이 책에서 제시한 예제가 조금은 낯설게 느껴졌습니다.
이유는 보통 null 관련 처리를 할 때에
스코프 안에서 처리를 하는게 아니라,
밖에서 null 체크를 하면서 진입하는 경우가 많기 때문입니다.

```kotlin
//책에서 제시한 예제
nullable.apply { println('my name is ${this?.name}') }

//보통 아래처럼 많이 사용
nullable?.apply { println('my name is ${this.name}') }
```

---

덧붙여서
일반적인 경우 != 무조건 이므로

우리 콕마켓 분들은 직접 비교해가며 더 가독성이 좋은 코드를 선택해가면 좋겠습니다!
