### ISSUE TITLE
[Chapter - 16] 상태를 설정할 때 함수 사용하기?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#26]
#### 질문 내용을 적어주세요 📝

책에서 지양해야 할 코드로 다음과 같은 코드가 나왔습니다.
```kotlin
class UserIncorrect {
	private var name: String = ""
    
    fun getName() = name
    
    fun setName(name: String) {
    	this.name = name
    }
}

class UserCorrect {
	var name: String = ""
}
```

저는 개인적으론 불변객체로 만드는 걸 선호하지만, 경우에 따라 이렇게 사용하기도 합니다. 
다들 어떤 방식을 선호하시는지 궁금하네요 ㅎㅎ
```kotlin
class User {
    var name: String = ""
        private set

    fun updateName(name: String) {
        this.name = name
     }
}
```

**Comment by sawooook** [comment]
저는 요렇게 했었습니다..! 업데이트 대상만 var로 ..!
근데 이 방식대로 하려면 setter는 사용안하기로 약속 하고 해야하는 방법 같긴합니다 ㅜ

```kotlin
    data class User(
       var name: String,
       val age: Int
    ) {
        fun updateName(name: String) {
            this.name = name
        }
    }
```

**Comment by ozzing** [comment]
저도 setter 사용을 지양하는 차원에서 사욱님과 동일하게 작성했었습니다!!

**Comment by JungTag** [comment]
JPA 엔티티 관련한 Q&A인데 요 내용이랑 비슷한 느낌이라서 공유드립니다~
https://www.inflearn.com/questions/593405/%EC%BD%94%ED%8B%80%EB%A6%B0%EC%9C%BC%EB%A1%9C-%EC%97%94%ED%8B%B0%ED%8B%B0-%EC%9E%91%EC%84%B1
