### ISSUE TITLE
[Chapter - 16] val을 이용할 때는 백킹 필드에 대한 레퍼런스인 field가 만들어지지 않는다?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#28]
#### 질문 내용을 적어주세요 📝

책에서 "참고로 val을 사용해서 읽기 전용 프로퍼티를 만들 때는 field가 만들어지지 않습니다."라는 내용이 나와서 테스트 해봤는데 잘 되네요..? 왜 책의 내용과 다른지 궁금합니다.
```kotlin
class TestModel {

    val name: String = ""
        get() = "Mr. $field" // OK
}
```

참고로 예제처럼 프로퍼티 값을 초기화하지 않는 경우에는 당연히(=프로퍼티 값이 없으므로) field를 사용할 수가 없네요. 이거는 var로 했을 때도 마찬가지로 안 되네요.
```kotlin
class TestModel {

    val name: String // error: Property must be initialized
        get() = "Mr. $field"


    var varName: String // error: Property must be initialized
        get() = "Ms. $field"
}
```

참고로 코틀린 버전은 1.8.22입니당

**Comment by eunq93** [comment]
아마 read-only property인 경우, 책에서는 함수값 리턴인 경우만 생각을 한 것 같네요.
결국 property에서 field식별자는 그 필드값 (위 질문에서는 name 변수)을 의미하는 거라서요.
JVM 에서 보면 this 으로 변환되는걸 확인할 수 있습니다.

```
class TestModel {

    val name: String = ""
        get() = "Mr. $field" // OK

    val name2 : String
        get() = "Mr $field"
}
```

```
public final class TestModel {
   @NotNull
   private final String name = "";
   @NotNull
   private final String name2;

   @NotNull
   public final String getName() {
      return "Mr. " + this.name;
   }

   @NotNull
   public final String getName2() {
      return "Mr " + this.name2;
   }
}
```
초기화가 되지 않은 변수라서 에러가 나오는것 같습니다.

공식문서에서 보듯. field는 이 클래스에서는 private String name 변수를 가리키는 식별자이니까요.
https://kotlinlang.org/docs/properties.html#backing-fields
