### ISSUE TITLE
[Chapter - 17] 이름 있는 아규먼트? 이름 있는 파라미터?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#29]
책에서 '이름 있는 아규먼트'와 '이름 있는 파라미터'라는 표현이 혼용되어 찾아보니 둘다 같은 의미로 사용하는 것 같습니다.
대부분의 CS 서적에서는 '이름 있는 파라미터(named parameter)'라는 용어가 더 보편적인 듯 합니다!!

**Comment by sawooook** [comment]
@JungTag 
오옹 ... 아규먼트는 전달해주는 값이고, 파라미터는 받는값 ? 으로 알고 있었는데,
이름있는 으로 사용될 경우에는 아규먼트랑 파라미터가 같은건가요?!

**Comment by JungTag** [comment]
@sawooook 
말씀주신대로 아규먼트는 실제 전달되는 값이고, 파라미터는 정의에 사용되는 변수고 실제 값을 어떻게 넘기는지에 대한 방법이기 때문에 사실 정확히는 '이름 있는 아규먼트'가 좀 더 정확한 표현 같습니당 ㅋㅋㅋ

공식문서에선 주로 named argument로 다루는 것 같더라구용 (아래 참조)
반면에 위키피디아에는 named parameter라고 나오고 제가 읽었던 몇몇 책들도 다 parameter 표현을 써서 전 '이름 있는 파라미터'로 정리했습니다!

ref)
https://www.tutorialspoint.com/what-are-named-parameters-in-chash
https://www.c-sharpcorner.com/UploadFile/manas1/named-and-optional-parameter-in-C-Sharp/
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments
https://kotlinlang.org/docs/functions.html#named-arguments
https://medium.com/dailyjs/named-and-optional-arguments-in-javascript-using-es6-destructuring-292a683d5b4e
https://blog.gitnux.com/code/javascript-named-parameters/
