### ISSUE TITLE
[Chapter - 06] 비즈니스 API를 설계함에 있어 표준 오류를 사용하는 것이 타당한가?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#3]
#### 질문 내용을 적어주세요 📝

아이템6는 이펙티브 자바에도 동일하게 나오는 내용인데, 위 내용은 당연히 라이브러리 개발자에겐 유용할 것 같습니다.
비즈니스 로직을 작성하는 데도 위 원칙을 적용해볼 수 있을지 논의해보면 좋을 듯 합니다.

**Comment by sawooook** [comment]
오옹 찾아보니 이런 글이 있네용..!
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/

커스텀 예외 사용하는 이유로 저는 4번 내용이 젤 공감 가긴 함니다...!

**Comment by JungTag** [comment]
@sawooook 
공감합니다. 표준 예외를 사용하자는 취지는 좋은데, 너무 범용적이다 보니 아래와 같은 문제가 있을 것 같네용
1) 어떤 표준 예외를 던져야 할지에 대한 고민
2) 추적이 힘듦
3) 개별 후처리
