### ISSUE TITLE
[Chapter - 20] 확장 함수를 사용하더라도 상태 변경이 가능하지 않은가?

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#30]
p.122에서 확장함수의 장점으로 다음과 같은 내용이 나오는데, 관련해서 의문점이 있습니다.

> 함수는 상태를 유지하지 않으므로 행위를 나타내기 좋습니다. 특히 부가 작용(side-effect)이 없는 경우에는 더 좋습니다.

이는 함수형 프로그래밍의 장점일 뿐 확장함수의 장점은 아닌 것 같다는 생각이 듭니다. (물론 코틀린에서 map, filter 등의 확장함수를 사용하여 함수형 프로그래밍을 할 수는 있는데, 이걸 말하는 건가 싶기도 합니다)

왜냐하면 확장함수 자체는 다음과 같이 상태를 변경할 수 있기 때문입니다.
```kotlin
fun Foo.update(A a, B, b) {
    this.apply { 
        a = a
        b = b
    }
}
```

위 내용에 대해서 좀 더 자세히 알려주시면 감사하겠습니다...!!!

**Comment by STACY-KH** [comment]
@JungTag 영택님 계속 찾아보다 다시 보니 혹시 가지고 계신 책에는 '함수는 상태는 유지하므로' 라고 나와 있나요?
제 책에는

> 함수는 상태를 유지하지 않으므로, 행위를 나타내기 좋습니다. 특히 부가 작용(side-effect)이 없는 경우에는 더 좋습니다.

라고 되어 있어서 이 문장의 이상한 점(?)을 못 찾아냈는데... 아님 제가 이해를 잘 못했을수도 있습니다..!

**Comment by JungTag** [comment]
@STACY-KH
제가 잘못 적었네요..!! 저 문장 자체의 문제라기 보다는 저게 확장함수의 장점이 맞나 싶었습니다.
확장함수와 대비되는 것으로 톱레벨 함수를 뽑았는데, 저런 특징은 톱레벨 함수도 마찬가지가 아닐까 해서요..!
