### ISSUE TITLE
[Chapter - 19] 언제 코드를 반복해도될까?

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#31]
#### 질문 내용을 적어주세요 📝

언제 코드를 반복해서 작성하시나요~?
자신만의 기준이 있다면 논의해보면 좋을것같아요

**Comment by seohw54** [comment]
* 대표적인 사례로 SP가 떠오르는데요..!
동일한 로직으로 작성되어있는 SP라도 사용하는 도메인이나 담당부서가 다르게 되면 반복해서라도 생성하는듯합니다.
SP의 특성일수도 있지만, 코드의 사용처가 여러곳이지만 요구사항이 달라질 가능성이 높은 경우 안정성을 위해 반복을 허용합니다.

* 프레임워크나 언어 자체가 아예 달라서 코드 재사용이 힘든 경우도 반복해서 작성하는듯합니다.
이런 경우는 외부적인 요인이긴 하지만, 저희 회사처럼 레거시를 신규플랫폼으로 전환하거나 다양한 플랫폼을 허용하는 경우에는 흔한 일인듯합니다.

**Comment by JungTag** [comment]
Request/Response 객체를 쓸 때 중복되는 프로퍼티가 많더라도 그냥 분리해서 작성하는 것을 선호합니다.
가끔씩 abstract class로 객체를 선언하고 상속하고 싶은 욕구가 들 때가 있는데, 그렇게 작성하면 나중에 스펙이 변경되면 유지보수가 힘들더라구요.. ㅎㅎ

**Comment by ozzing** [comment]
저도 영택님처럼 중복되는 프로퍼티가 많아도 Request/Response 역할에 따라 분리하는 것 같습니다!

또, if-else 문에서 케이스가 딱 두가지인 경우에 코드가 아주 조금 다르다면 엄청 선호하지는 않지만 그냥 두기도 하는 것 같습니당
중복되는 코드가 메소드로 뺄만큼 '한 개의 기능'이라고 보기 어려운 경우에 주로 그런것 같아요!
