### ISSUE TITLE
[Chapter - 17] 함수의 타입 파라미터가 성능에 영향을 주는가?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#34]
#### 질문 내용을 적어주세요 📝
p.98에서 이름 있는 아규먼트를 사용할때 타입을 사용할 경우 성능이 걱정되면 인라인 클래스를 사용하라고 되어있는데요~
아규먼트에 타입이 있으면 왜 성능 저하가 우려되는것인지 궁금합니다.

아규먼트에 타입이 있는것은 일반적이고, 명시적으로 선언한다면 성능 저하가 될것같지 않은데, 
책에서 요렇게 말한 이유가 궁금합니다!

**Comment by JungTag** [comment]
우선 p.98에서는 말하는 타입이란 아래와 같은 래퍼 타입을 의미합니다.
```kotlin
sleep(Millis(100))

// 타입 선언
data class Millis(val value: Int)
```

여기서 별도의 래퍼 타입을 선언하여 값을 넘기면 숫자 리터럴을 넘길 때보다 명확하게 의미를 드러낼 수 있고, 안전하게 코드를 작성할 수 있다는 장점이 있습니다. 그러나 인스턴스 생성 과정에서 오버헤드가 발생한다는 단점이 있습니다. (코틀린 공식문서에 의하면 래핑되는 타입이 원시 타입인 경우엔 성능이 매우 떨어진다고 하네요)

inline class를 사용하면 컴파일 시점에 별도의 객체 생성 없이 프로퍼티 타입 그대로 치환되므로 이러한 오버헤드 없이 래퍼 타입을 사용할 수 있습니다.
```kotlin
@JvmInline
value class Millis(private val s: Int) // 컴파일 시점에 Int로 치환!!
```

ref) https://kotlinlang.org/docs/inline-classes.html
