### ISSUE TITLE
[Chapter - 24] 왜 객체 내부에선 업캐스트 객체에 convariant를 사용할 수 없을까?

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#37]
#### 질문 내용을 적어주세요 📝
제네릭 나오니까 내용이 빡세네여...

> 141P

객체 내부에선 업캐스트 객체에 convariant를 사용할 수 없다 라고 나오는데 왜 사용하지 못할까요?!

**Comment by JungTag** [comment]
저는 "공변은 서로 다른 제네릭 타입(`Box<Dog>`, `Box<Puppy>`)간의 문제, 즉 객체 외부 간의 타입에 대해 다루는 것이고, 객체 내부적으론 제네릭 타입이 아닌 실제 타입 매개변수(`Puppy` = 업캐스트 객체)만을 다루기 때문에 공변을 사용할 수 없다."라고 이해했습니다.
