### ISSUE TITLE
[Chapter - 24] 공변/불공변과 관련된 자료

### ISSUE THREAD

**Issue by JungTag** [ko-auction/effective-kotlin#40]
예전에 공변 관련해서 공부할 때 도움을 많이 받았던 자료들입니다(사실 지금 까먹어서 다시 봐야하는).
챕터 24가 어렵다보니 도움이 될까 하여 공유드립니다~

1) Java/Kotlin 공변 (part1+part2)
https://asuraiv.tistory.com/16
https://asuraiv.tistory.com/17

2) 제네릭 변성 (최범균님 영상)
https://youtu.be/PtM44sO-A6g

**Comment by sawooook** [comment]
진짜 맨날 볼때마다 까먹네욤 ...ㅜ

공유 감사합니당
