### ISSUE TITLE
[Chapter -21] 코틀린 Property Delegator 종류 ?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#41]
#### 질문 내용을 적어주세요 📝
p.129에 범용적으로 사용되는 Delegator에 대해 소개를 했는데요~
책에서 소개한 것 이외에 아래 델리게이터들은 어떤 동작을 하는지, 주로 어떤곳에서 활용할 수 있는지 궁금합니다!
(vetoable은 책에 언급되긴 했지만 약간은 생소하여 같이 질문 드립니다~!)

* Delegates.vetoable
* Delegates.storing
* Delegates.softReference

**Comment by JungTag** [comment]
이거 제가 착각하고 아이템 21 정리했어서 대신 답변드립니다 ㅋㅋ

- [lazy](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/lazy.html): 람다를 통해 호출되는 시점에 프로퍼티를 초기화한다 (지연 초기화) (lazy과 lateinit의 차이는 [여기](https://github.com/ko-auction/effective-kotlin/issues/36)를 참고)
- [Delegates.observable](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.properties/-delegates/observable.html): 값에 변화가 생기면 콜백 함수를 수행한다
- [Delegates.vetoable](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.properties/-delegates/vetoable.html): 값의 변경 시 특정한 조건(콜백 함수가 Boolean을 반환)에 따라 변경을 취소할 수 있다
- [Deleagates.notNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.properties/-delegates/not-null.html): 지연 초기화되는 프로퍼티를 반환하는 위임자
  - 지연 초기화를 수행하는 점에 있어 lazy와 동일하지만 그 동작에 있어선 차이가 있다
  - Delegates.notNull은 해당 프로퍼티가 바로 초기화될 수 없지만, not null임을 보장하고 싶을 때 사용된다 (초기화 되지 않거나 null이라면 에러가 발생한다)
  - lazy는 콜백 함수를 실행시킴으로써 접근 시점에 프로퍼티를 초기화한다

**Comment by sawooook** [comment]
영택님이 어떤 동작을 하는지 적어주셔서 저는 어디에 활용 할 수 있는지 적어보겠습니다..!
- lazy 
- Delegates.observable : UI 변경시에 활용할 수 있을 것 같습니다, 버튼이 클릭 되면 콜백을 실행한다? 이런느낌으로?
- Delegates.vetoable : 유효성 검사에 통과할 경우 객체가 이름을 갖을 수 있도록 쓸 수 있을것 같습니다 ?
```kotlin
class User {
    var name: String by Delegates.vetoable("") { _, _, newValue ->
        if (newValue.isNotEmpty()) {
            true
        } else {
            false
        }
    }
}
```
- Delegates.notNull : 무조건 초기화가 필요한경우 ...? 회원가입 같은곳에서 사용하면 할 수 있을것 같기도합니다! User 객체의 값이 안차면 안된다...?

**Comment by seohw54** [comment]
ㅎㅎ답변 감사드립니당 !!
아래 2개 델리게이트는 표준 코틀린 라이브러리로 제공하는것은 아니고 그냥 구현해서 쓰는 패턴이었네요..!

* Delegates.storing : 초기 값을 제공하면서 프로퍼티의 값을 저장

```kotlin
fun <T> storing(initialValue: T): ReadWriteProperty<Any?, T> {
    var value: T = initialValue
    return object : ReadWriteProperty<Any?, T> {
        override fun getValue(thisRef: Any?, property: KProperty<*>): T {
            return value
        }

        override fun setValue(thisRef: Any?, property: KProperty<*>, value: T) {
            this.value = value
        }
    }
}

..
var name by storing("John")

``` 
* Delegates.softReference : 메모리가 부족할때 해당 객체를 가비지 컬렉터가 자동으로 회수할 수 있는 SoftReference로 객체를 생성해준다.
(참고) https://medium.com/@pgopinath/idiomatic-weakreference-implementation-by-delegate-in-kotlin-65ec60287de6

```kotlin
fun <T> softReference(): ReadWriteProperty<Any?, T?> {
    var reference: SoftReference<T>? = null
    return object : ReadWriteProperty<Any?, T?> {
        override fun getValue(thisRef: Any?, property: KProperty<*>): T? {
            return reference?.get()
        }

        override fun setValue(thisRef: Any?, property: KProperty<*>, value: T?) {
            reference = if (value != null) SoftReference(value) else null
        }
    }
}

..
var name by softReference<String>()

```
