### ISSUE TITLE
[Chapter - 28] Experimental 메타 어노테이션

### ISSUE THREAD

**Issue by ozzing** [ko-auction/effective-kotlin#44]
#### 질문 내용을 적어주세요 📝
안정적인 API에 새로운 요소를 추가한다면, Experimental 어노테이션을 통해 해당 요소가 안정적이지 않음을 알려주는 것이 좋다고 기술되어 있는데요..!
해당 어노테이션의 level들과, 설정된 레벨에 따라 어떤 때에 사용하는 것이 좋을지 궁금합니다!

**Comment by sawooook** [comment]
어머나 `Experimental`은 `deprecated` 되어부렸네용
![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/406d8f6c-3088-423b-9b9c-79c1344a504e)

+ `Warning`의 경우 해당 기능은 변경가능성이 있다 라고 알려줄때 사용하면 좋을것 같습니다
인텔리제이가 노란색으로 불편하게 만들면서... 상위클래스에 더 선언하라고 변경가능한 실험적인 기능이 포함된거다 라고 표시하라고 알려주고있네용
![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/96ed545e-13e5-40f1-8dcd-97765d42c48d)


+ `Error` 는 해당 기능을 사용하면 오류가 발생한다고 알려줄때 사용하면 좋을것 같습니다..! 심지어 컴파일단에서 빌드까지 안되도록 막히네용..!
![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/fef09f6c-89b0-4e61-a764-e53f463f56e8)



이제 대체 할수 있는 `RequiresOptIn` 을 알아보겠습니다..!
![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/7a5dee77-2469-462d-b478-aa62dd1437d7)
기존 기능은 비슷비슷한데 추가로 메세지를 남길 수 있도록 되어있네용..!
