### ISSUE TITLE
[Chapter-25] 코틀린 백엔드 프레임워크 ktor ?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#45]
#### 질문 내용을 적어주세요 📝
p.148에서 코틀린의 백엔드 프레임워크인 ktor에 대해 언급되어 있는데요~
경량화된 웹 개발시 적합하다고 되어있긴한데, 
구체적으로 어떤 특징이 있는지,spring 이랑 어떤 차이가 있는지 궁금합니다!

**Comment by ozzing** [comment]
**Ktor의 특징은 다음과 같습니다!**
1. 서버와 클라이언트(웹/모바일) 개발에 모두 사용 가능
- web applications
- HTTP service
- mobile application
- browser application
2. 어플리케이션 생성, 라우팅 설정만으로도 구현 가능
```kotlin
// Application
fun main() {
    embeddedServer(Netty, port = 8080, host = "0.0.0.0") {
        configureRouting()
    }.start(wait = true)
}

// Routing
fun Application.configureRouting() {
    routing {
        get("/") {
            call.respondText("Hello World!")
        }
    }
```
![image](https://github.com/ko-auction/effective-kotlin/assets/63996052/c145a1d0-ad76-4240-8043-8de3e5c1b3b5)
출처: https://jyami.tistory.com/150

3. 코루틴(Coroutine) 기반의 비동기 프로그래밍
https://wooooooak.github.io/kotlin/2019/08/25/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%BD%94%EB%A3%A8%ED%8B%B4-%EA%B0%9C%EB%85%90-%EC%9D%B5%ED%9E%88%EA%B8%B0/

4. 간편한 의존성 주입 (Kotlin Injection 라이브러리 Koin)
```kotlin
// Spring
@Bean
fun findItem() = FindItem(...)

// Koin
single { FindItem(...) }
```
- 어노테이션이 아닌 DSL 방식으로 작성 가능
- Spring에 비해 가벼운 컨테이너

5. 데이터베이스 연동
```kotlin
// Exposed
StarWarsFilms
  .slice(StarWarsFilms.sequelId.count(), StarWarsFilms.director)
  .selectAll()
  .groupBy(StarWarsFilms.director)
```
- SQL문을 직접 작성하는 것보다 명시적
- Spring은 DSL 방식을 사용하기 위해 추가 라이브러리 필요, Ktor는 기본 제공

공식 문서: https://ktor.io/docs/welcome.html
