### ISSUE TITLE
[Chapter - 33] 팩토리 함수들 언제 사용할 수 있을까?

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#52]
#### 질문 내용을 적어주세요 📝

책에보니까 5개의 팩토리 함수가 나오더라구요
1. companion 객체 팩토리함수
2. 확장팩토리함수
3. 톱레벨 팩토리함수
4. 가짜 생성자
5. 팩토리 클래스의 메서드

저는 일반적으로 1번 만 이용해서 객체를 생성하는데
나머지 4개는 각각 어느 상황에서 사용하면 좋을까용?!??!

**Comment by seohw54** [comment]
* 확장 팩토리 함수
코틀린의 표준 라이브러리로 제공되는 클래스의 객체를 커스텀하게 생성할때 사용하면 좋은듯합니다.
아래 코드에서처럼 Int형의 일정 범위에 맞는 난수를 생성하는 메소드를 이미 표준라이브러리로 있는 Int의 확장함수로 구현하여 사용할 수 있습니다.
이외에도 Date 관련 유틸 메소드들을 구현할때 많이 사용됩니다.

```kotlin
fun Int.Companion.randomInRange(start: Int, end: Int): Int {
    require(start <= end) { "Invalid range" }
    return (start..end).random()
}

fun main() {
   Int.randomInRange(1,10)
}
``` 

* 톱레벨 팩토리 함수
클래스 여러 곳에서 사용하는 유틸성 함수들을 톱레벨 팩토리로 만들면 좋은듯합니다.

* 가짜 생성자
p.216에서 사용하는 코드를 보면 좋을 것 같습니다...!
List, MultableList는 인터페이스기 때문에 생성자를 가질 수 없습니다. 
하지만 아래처럼 정의된 inline 함수 덕분에 생성자처럴 사용할 수 있고 객체를 생성하게 됩니다.
이처럼 인터페이스이지만 일반 클래스처럼 객체를 생성하는 팩토리 함수를 만들고 싶을때 사용합니다.

```kotlin
List(4) { "User$it"}

public inline fun <T> List(size: Int, init: (index: Int) -> T): List<T> = MutableList(size, init)

public inline fun <T> MutableList(size: Int, init: (index: Int) -> T): MutableList<T> {
    val list = ArrayList<T>(size)
    repeat(size) { index -> list.add(init(index)) }
    return list
}
``` 

* 팩토리 클래스의 메소드
근화님이 질문주신 이슈에 답변드린 코드로 보시면 좋을것 같습니다.
프로퍼티가 필요한 추상 팩토리를 구현하거나 캐싱처리를 하는 경우입니다!

https://github.com/ko-auction/effective-kotlin/issues/50
