### ISSUE TITLE
[Chapter - 43] 확장은 가상이 아니다

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#55]
#### 질문 내용을 적어주세요 📝

> 295p
확장은 가상이 아니라는 것입니다.

라는 내용이 나오는데요...! 왜 확장함수는 정적으로 동작하는것일까요?

가상이라는게 조금 와닿지 않네여 ...

**Comment by JungTag** [comment]
먼저 virtual class는 abstract class와 정도로 생각해주시면 될 것 같습니다.
질문에 답을 해보자면 **다형성을 지원하지 않기 때문에** 정적으로 동작한다고 볼 수 있습니다.
컴파일 과정에서 메서드의 첫 번째 인자에 자기 자신에 대한 참조가 들어가므로 메서드 시그니쳐가 일반 상속 가능한 함수와 달라지고, 오버라이딩이 불가능하게 됩니다.
