### ISSUE TITLE
[Chapter - 47] 왜 inline class는 단일프로퍼티 밖에 못갖는가 ?!

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#56]
#### 질문 내용을 적어주세요 📝
> p330 하나의 값을 보유하는 객체도 inline ... 

라고 적혀있어 만들어 봤는데용

왜 inline class는 하나의 프로퍼티 만 가질 수 있는지 궁금합니다..!

![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/86163892-693d-42df-b766-455d04fd3c9e)

추가로 IDE 에서 `inline` 을 없애고 `@JvmInLine` 요걸 추천해주던데 무슨 기능적 변화가 있는지도 궁금합니당 ㅎㅎ

![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/3711ff29-ff8c-46d2-badd-4a74fbf9a6b6)

**Comment by seohw54** [comment]
### **1. 왜 inline class는 하나의 프로퍼티 만 가질 수 있는지?**

인라인 클래스는 객체의 래핑타입을 지원하는 용도이기 때문에 1개의 프로퍼티만을 가질 수 있습니다.
예를 들어서, Integer클래스의 필드가 2개가 아니고 1개인것 처럼, 인라인 클래스가 감싸고 있는 대상은 단일 내부객체입니다.
사욱님이 예시로 적어주신 코드를 랩핑하는 용도로 사용할 경우에는 아래처럼 변경할 수 있을듯 합니다..!

```kotlin
class User(
    private val name: String,
    private val age: Int
)

inline class WrappedUser(private val user: User)

fun main () {
    val wrapperUser : WrappedUser //컴파일시점에 WrapperUser타입은 User타입으로변환!
}
``` 


### **2. inline과 @JvmInLine 차이?**

inline은 코틀린1.3부터 지원됐고, @JvmInline은 1.5부터 지원이 됐습니다. 

사용자 입장에서 기능적으로는 사실상 차이가 없으나, 
@JvmInline은 자바나 코틀린의 다른 버전(Koelin/JS, Kotline/Native)에서 value class 호환을 해주고 있습니다.

따라서 코틀린 버전 업그레이드에 따라 inline class -> @JvmInline 및 value class 로 키워드가 변경됐다고 생각하시면 됩니다.

키워드가 변경된 이유가 있는데, 다들 잘 아시다시피 코틀린에서는 inline function이 별도 존재 합니다. 
inline class와 키워드가 동일하긴 하지만 내부 컨셉 자체가 아예 다르기 때문에 혼란을 주고 있어 inline class의 키워드가 변경되었다고 합니다.
