### ISSUE TITLE
[Chapter - 07] sealed 클래스는 왜 else 문을 안써도 될까?

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#6]
`sealed class` 는 분기 처리를 할때 else문을 안써도 됩니다...!

```
    sealed class Result {
        data class Success(val data: String) : Result()
        data class Error(val message: String) : Result()
    }

    fun processResult(result: Result) {
        when (result) {
            is Result.Success -> println("성공!") 
            is Result.Error -> println("에러!")
        }
    }
```

그럼 else문을 안써도 되는것을 어떻게 sealed class는 보장해주는것일까?
sealed class 는 클래스의 하위 클래스 값들을 모두 컴파일시에 등록 해 준다고합니다.
그러기 때문에 컴파일 후 에는 추가로 구현체들이 추가될 수 없습니다

그러기 때문에 명확하게 하위 값들이 어떤것인지 알고 있기에 else 문을 안쓰도록 보장해줍니다..!

Q. 그럼 일반 클래스들은?
컴파일 시점에 하위 클래스 값들이 등록 되지 않습니다. 동적으로 계속해서 변할 수 있기에 ( 유연성과 확장성을 위해 ) 컴파일러는 모든 하위 클래스를 추적하거나 분기 처리하는것은 보장 할 수 없습니다..!

그래서 else문을 사용하여 처리해줘야합니다..!

읽어보면 좋을만한 글
+ https://kotlinlang.org/docs/sealed-classes.html

**Comment by JungTag** [comment]
맨날 의미없는 else 문을 사용하라는 경고가 떠서 왜 그런지 했는데 이런 이유가 있었군요 ㅋㅋㅋㅋ
좋은 정보 감사합니다. 저희 비즈니스 로직에도 sealed class를 적용할 수 있는 케이스가 많을 것 같아요 ㅎㅎ
