### ISSUE TITLE
[Chapter - 07] try catch 문을 사용하면 왜 비용이 비쌀까?

### ISSUE THREAD

**Issue by sawooook** [ko-auction/effective-kotlin#7]
try catch문을 사용하면 비용이 많이 발생한다고 합니다..!

why?
1. 예외객체 생성
일단 예외가 발생하면 예외객체를 생성합니다 `NotFoundException()` 추가 객체를 생성하기 때문에 비용이 발생합니다.
2. 예외처리흐름의 전환
예외가 발생하면 예외 핸들러로(`@ExecptionHandler`) 전환이 됩니다. 이는 호출하는 스택을 변경하는 작업이 들어가고, 정상 작동 코드와 다른 경로로 따라가므로 추가 비용이 발생합니다

역시 적절하게 사용하는것이 좋겠네용..!

관련 글
+ https://january-diary.tistory.com/entry/JAVA-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%EC%9D%98-%EB%B9%84%EC%9A%A9
+ https://meetup.nhncloud.com/posts/47

**Comment by JungTag** [comment]
좋은 의견 공유 감사합니다 ㅎㅎ 관련해서 궁금한 게 몇 가지 있습니다.
1. 예외객체 생성
 -> catch 문에서 새로운 익셉션을 생성하는 케이스에 대한 건지 궁금합니다! 그냥 catch에서 다른 처리를 해버리고 return 해버리면 특별한 생성 비용은 들지 않을 것 같아서요!
2. 예외처리흐름의 전환 ->try/catch로 예외를 잡지 않고 그냥 전파되는 케이스에도 동일하게 발생하는 게 아닌가 싶습니다..!
