### ISSUE TITLE
[Chapter - 08] nullable enum 사용 용도?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#8]
#### 질문 내용을 적어주세요 📝

p.58 "nullable enum과 none enum 값은 완전히 다른 의미이며,
null enum 은 별도로 처리해야 하고, none enum은 정의에 없으므로 필요한 경우에 사용하는 쪽에서 추가해서 활용 가능하다."

nullable enum이 필요한 상황이 있을지 궁금합니다. 
enum 자체가 상수에 대한 열거형이고 null로 표현이 필요하다면 (enum값 중 해당되는 것이 없는 나머지 경우)
none 값으로 대체하면 되는 것이 아닐지 싶어서요!

**Comment by JungTag** [comment]
우선 저는 해당 구문을 대응되는 이넘 상수가 없을 땐 nullable 타입 대신, 대응되는 값이 없음을 표현하는 상수(ex) None)을 사용하라는 것으로 이해했습니다. 즉, nullable enum 사용을 지양하고 의미를 갖는 enum을 사용하라는 것으로 이해했습니다.
```kotlin
Constant? // nullable enum -> bad
Constant.None // None enum -> good
```

사실 nullable enum이 필요한 상황은 전혀 없을 듯 한데.. NPE의 위험을 가진 값을 굳이? 사용할까 싶습니다.
여기에 그 이유가 잘 설명되어 있는 것 같습니다.
https://softwareengineering.stackexchange.com/questions/268198/nullable-enumeration-values-vs-novalue-or-undefined-etc

어쨌든 제 생각엔 "그렇게 해야 할 필요가 없다."라는 것이 결론입니다.
굳이 nullable로 만들어서 elvis 연산자나 null safe 연산자를 사용할 수는 있겠지만, 그럴 바에야 enum class 내에 메서드를 정의해서 사용하는 게 나을 듯 하네요.
