### ISSUE TITLE
[Chapter - 07] unchecked 예외란 무엇인가?

### ISSUE THREAD

**Issue by seohw54** [ko-auction/effective-kotlin#9]
#### 질문 내용을 적어주세요 📝

p.48 맨 아래 줄에 "코틀린의 모든 예외는 unchecked 예외 입니다. 
따라서 사용자가 예외를 처리하지 않을 수도 있으며, 이와 관련된 내용은 문서에도 제대로 드러나지 않습니다."

라고 적혀있는데요. 주석에 "처리하지 않아도 실행에 문제가 없는 예외" 라고 적혀있긴한데, 
구체적인 예시가 궁금합니다.

그리고 코틀린이 아닌 다른 언어에서는 checked 예외가 될수 있는건지도 궁금합니다!

**Comment by sawooook** [comment]
일단 코틀린은 모든 예외가 uncheked예외이기 때문에 자바로 설명드리겠습니다~!

일단 checked 예외의 경우 컴파일시점에 걸러지기 때문에 `try catch` 표현을 한다던가 `throws Exception` 을 통해 표시를 해줘야 실행이가능합니다
![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/dcfc6f1d-2c00-4563-83f6-9843ffd3f20f)

그러나 unchecked의 경우에는 RuntimeException 이므로 처리하지 않아도 실행에 문제가 없는 예외입니다..!
![image](https://github.com/ko-auction/effective-kotlin/assets/43979984/c1c8bb99-b687-468c-b26b-a57b48a6483f)


일단 자바는 checked 예외가 있습니다..!

요거 보니까 블로그글에 요런 말이 있네욤..!
https://velog.io/@eastperson/Java%EC%9D%98-Checked-Exception%EC%9D%80-%EC%8B%A4%EC%88%98%EB%8B%A4-83omm70j

> 코틀린은 exception을 자바에게 상속받았음에도 불구하고 자바와 동작을 달리한다. 다른 최신 언어들처럼 코틀린 개발자도 Checked Exception을 포함하지 않기로 했다. - Kotlin In Action

> 자바는 checked exception에 대한 실험을 했고 실패했다. 따라서 Ruby나 C# 처럼 자바의 영향을 받았던 언어에서도 checked exception을 사용하지 않는다.

**Comment by sawooook** [comment]
코틀린은 왜 checked 예외를 채택하지 않았는가에 대해서 찾아보니

1. 대부분 개발자들은 checked 예외처리할때 catch를 비워둔다...
2. 소규모 프로그램에서는 코드품질을 향상시킬수 있지만, 대규모 프로그래밍에선 그렇지 않다.
3. try catch 가독성이 별로다
